### PR TITLE
SVProgressHUD removal

### PR DESCRIPTION
**Pull request by zobkiw**
First pass at simple HUD - StatusHUD.storyboard can be tweaked to change colors, transparency, etc.

I am currently not taking into account the UIAccessibilityScreenChangedNotification - since this is working slightly differently than the other hud I'd like to find out if it is even required before implementing it.

image

### CODE REVIEW

**Comment by hburgund** [comment]
Initial testing shows that this performs as desired in most cases. Some notes:

* The one case that is missing that we should probably have (can't remember if we had it before, but I assume not) is the case when a new tag is selected while the stream is playing. This should have the "remixing" message.
* The accessibility focus never goes to the HUD, so VoiceOver never plays the message in the HUD. This needs to be fixed first and then I can see where the focus goes after the HUD is hidden.
* Because of this, I think, the HUD isn't truly modal for VoiceOver meaning that all the underlying view's elements can still be swiped through with VO, though they cannot be actually tapped.
* The minimum display time works nicely, but can we add a maximum time as well? It is possible to get the HUD stuck in display mode if you do things like try to replay an asset when no asset is playing. Clearly, the skip/replay buttons should be disabled when there is no asset playing, but I feel like if it is simple to add a maximum time, that would be a good catch-all for any random situations that might occur.

**Comment by sinabahram** [comment]
We don’t even need the focus to go to the HUD, as long as VO announces it’s contents, which can be made to happen with various API calls. I’m simply trying to minimize effort here. especially if it’s going to simply disappear after 500ms or whatever period of time the loading operation takes.

Happy to discuss further. If it’s possible to have focus go there, of course that’s preferable, but what we definitely are trying to avoid is having things be swipeable and tappable that aren’t actually able to do anything because they are “modal”.

**Comment by zobkiw** [comment]
- "Remixing" message ok
- Adding a maximum display time sounds like it is covering a bug. Every show should be balanced with a hide. Yes this can be added as a "safety feature" but it doesn't sound like the proper solution if this particular case causes trouble. I would suggest writing that up as a separate issue to address.
- Regarding the HUD voiceover - I like @sinabahram's idea of having the VO announce the text string instead of messing with the modality aspect of things.

**Comment by hburgund** [comment]
Yes, as I said, the maximum display time is definitely a catch-all and in theory should be solvable by a number of other more "proper" solutions. My concern is that much of the time the hiding of the HUD is triggered by stream metadata, so not everything is under the client's complete control and might be thrown off my unexpected server behavior. 

I don't want to dive deep into all the different possibilities and edge cases for stream metadata if possible, so I thought this might be the best approach at this point. But if you guys disagree, I am happy to try to be more rigorous and specific and can create a new issue at that point.

**Comment by zobkiw** [comment]
Every API call results in a success or failure (either by timeout or by the server responding negatively) - as long as all of these cases are handled (ie: rw*Success and rw*Failure callbacks for each call) then this should never be a problem. Maybe some of them are missing. I agree that spending time to dig into this right now may not be the best use of aforementioned time so whatever you prefer now is fine.

**Comment by hburgund** [comment]
OK, let's do the quick and dirty maximum time for the HUD display as I think that's the best way to avoid getting into major weeds right now.

@sinabahram can you explain (perhaps with code examples or links) more about how you are suggesting we can get VO to announce the contents of the HUD without requiring a focus shift? Are we simply talking about forcing VO to speak a particular string at a particular time regardless of focus?

I do have a concern about if we go this direction, how do we prevent the underlying view from being accessible by swiping etc to VO users? To reiterate, my (albeit somewhat naive) testing showed that while the HUD was in place, I could swipe between elements in the underlying view though I could not actually tap/activate/trigger them. Should we just use some other call to disable VO on all elements while the HUD is in place or something? Please advise!

@zobkiw has time tonight to wrap everything here up, but needs some guidance to do so efficiently.

**Comment by zobkiw** [comment]
OK on timeout.

Regarding voice: maybe we do something like read the text on show "Remixing audio..." and add "please wait..." then when the hud hides we have it say "Remixing audio complete." This at least prompts the user that even though they can traverse the elements they are not really accessible during this time.

**Comment by sinabahram** [comment]
That “technically” breaks things, but I hear you. is it possible to apply a “dimmed” state on the whole view? That way VoiceOver would report that they aren’t accessible even though they are traversable?

**Comment by zobkiw** [comment]
The whole view is dimmed with the hud visible.

**Comment by sinabahram** [comment]
Ok, happy to test this with a push of the app, but @Hburgund, did you have VO reporting that they were dimmed/disabled?

**Comment by zobkiw** [comment]
A view was put over the entire screen which caused everything to look dimmed. What does VOA look for specifically to tell if this is the case? 50% opacity or less? Some other trigger?

**Comment by hburgund** [comment]
I did not notice any indications via VO that the screen was dimmed. As far as I can tell, right now, there is no way a VO user would know that the modal was in place. I can test again if you let me know what specifically to look for, but I think we are just visually dimming and in so doing, restricting access to the below view by all touch events going to the top view.

**Comment by sinabahram** [comment]
The actual dimmed/disabled state. That was what I was getting at in terms of semantically disabling them.

**Comment by sinabahram** [comment]
Is the User Interaction Enabled trait set to NO? If so, then Halsey, you hear VO say “dimmed” as part of the control announcement.

**Pull request merged**
