### PR TITLE
~ Build 20

### PR DESCRIPTION
**Pull request by seeReadCode**
Here's the pull request from my fork.

I'll pull over the open issues once this is merged.

### CODE REVIEW

**Comment by seeReadCode** [comment]
pinging you @hburgund on the off chance you didn't get an email from this PR

**Comment by hburgund** [comment]
Yes, I got the notification. This is obviously a very large PR and appears to be pretty much everything you have done? Is this just a dump of your work into the main repo or is there something specific to test here for which you are issuing the PR?
Just give me some context/rationale so I know what you need from me. If you don't need any testing/review, I can merge right away, but otherwise, I'm not going to be able to really get into it until the weekend as I'm in SF for the rest of this week...

**Comment by seeReadCode** [comment]
This is all of the work done to date. My understanding is that you wanted the commit history and then I would copy over the remaining issues.

**Comment by hburgund** [comment]
yes, I do want the commit history. I can rebase as necessary to clean things up.

I will assume you are just looking for this to be merged to get it into the official repo and not for me to do specific testing prior. LMK ASAP if not!

**Comment by seeReadCode** [comment]
Yep, I'm just trying to get the app and framework on your forks so that we can have the code in place for hand off ASAP.

**Comment by sinabahram** [comment]
Just to add to this, this is the transfer so we can start handing off work into the proper repositories, etc.

**Pull request merged**
